"""empty message

Revision ID: 85279f17ed8e
Revises: defff4376072
Create Date: 2020-12-20 11:14:18.050856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85279f17ed8e'
down_revision = 'defff4376072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.transaction_timestamp(), nullable=True))
    op.add_column('addresses', sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.transaction_timestamp(), nullable=True))
    op.add_column('inventory_locations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.transaction_timestamp(), nullable=True))
    op.add_column('inventory_locations', sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.transaction_timestamp(), nullable=True))
    op.add_column('item_images', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.transaction_timestamp(), nullable=True))
    op.add_column('item_images', sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.transaction_timestamp(), nullable=True))
    op.add_column('items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.transaction_timestamp(), nullable=True))
    op.add_column('items', sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.transaction_timestamp(), nullable=True))
    op.add_column('items_info', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.transaction_timestamp(), nullable=True))
    op.add_column('items_info', sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.transaction_timestamp(), nullable=True))
    op.add_column('owners', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.transaction_timestamp(), nullable=True))
    op.add_column('owners', sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.transaction_timestamp(), nullable=True))
    op.add_column('sellers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.transaction_timestamp(), nullable=True))
    op.add_column('sellers', sa.Column('updated_at', sa.DateTime(timezone=True), onupdaspte=sa.func.transaction_timestamp(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'updated_at')
    op.drop_column('sellers', 'created_at')
    op.drop_column('owners', 'updated_at')
    op.drop_column('owners', 'created_at')
    op.drop_column('items_info', 'updated_at')
    op.drop_column('items_info', 'created_at')
    op.drop_column('items', 'updated_at')
    op.drop_column('items', 'created_at')
    op.drop_column('item_images', 'updated_at')
    op.drop_column('item_images', 'created_at')
    op.drop_column('inventory_locations', 'updated_at')
    op.drop_column('inventory_locations', 'created_at')
    op.drop_column('addresses', 'updated_at')
    op.drop_column('addresses', 'created_at')
    # ### end Alembic commands ###
