"""empty message

Revision ID: cd4da29b72b5
Revises: ac9332db67f0
Create Date: 2020-12-18 19:59:43.850455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4da29b72b5'
down_revision = 'ac9332db67f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_types', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.alter_column('items', 'item_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'item_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('item_types', 'created_at')
    # ### end Alembic commands ###
