"""empty message

Revision ID: defff4376072
Revises: cd4da29b72b5
Create Date: 2020-12-20 08:57:54.036067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defff4376072'
down_revision = 'cd4da29b72b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_types', sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.transaction_timestamp()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_types', 'updated_at')
    # ### end Alembic commands ###
